"""adiciona campo sexo ao animal

Revision ID: 18e7eb7efd77
Revises: 1af781d5cd09
Create Date: 2026-08-25 20:41:32.058243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e7eb7efd77'
down_revision = '1af781d5cd09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
